Implement Docsify
pokemon-speedrunning/speedrun-routes pull request #10
Opened 2020-10-11 06:41 UTC by TiKevin83

Reorganizes the repo for docsify

-everything in the docs folder, major routes renamed to README
-can test with the following:
```
npm i docsify-cli -g
docsify serve docs
```

2020-10-11 13:17 UTC, sizzle-psr commented
This looks very good, but the resources are giving a 404 when trying to access them. I assume we need to set these links up in another way. Is this something for this PR or are we not too concerned with with these links for the moment?

2020-10-11 18:53 UTC, TiKevin83 commented
I fixed relative links to resources by adding `relativePath: true` to the docsify configuration - you should also be able to access them directly at a url like this:

http://localhost:3000/#/gen-1/red-blue/main/glitchless/resources/postnerd-backup-paras

I'd like to add them all to the sidebar too

2020-10-12 10:58 UTC, sizzle-psr requested changes

2020-10-12 10:58 UTC, sizzle-psr commented on docs/gen-2/gold-silver/main/glitchless/resources/README.md
> +* [LID Frames](lid-frames.md)
This should be `LID-frames.md`.

Instead of changing this name however, I suggest changing the name of the file to `lid-frames.md`

2020-10-12 10:58 UTC, sizzle-psr commented
See above review, otherwise, everything seems to be working and indexing seems to be automatically created for the guides, which is amazing.

2020-10-12 11:09 UTC, sizzle-psr approved these changes

2020-10-12 11:10 UTC, merged